### ISSUE TITLE
[Prototype] Placement des batiments sur la map

### ISSUE THREAD

**Issue by Aymerix01** [Aymerix01/Cassiopee#5]
L'objectif est de pouvoir placer un bâtiment sur la map comme on peut le voir sur les images suivantes :

![Capture d'écran 2023-11-17 180909](https://github.com/Aymerix01/Cassiopee/assets/123820772/d212e4e5-be7d-48c1-b002-c11d8c414f05)
![Capture d'écran 2023-11-17 180848](https://github.com/Aymerix01/Cassiopee/assets/123820772/bb5000e9-9696-4b09-af1a-a73a8ee08fd6)

Comme il s'agit d'un prototype, on utilisera des cubes pour la map et pour les batiments:

![UE4_Rotate_Cube-1](https://github.com/Aymerix01/Cassiopee/assets/123820772/e956f6e2-cac0-4812-be58-366381be140c)

Information technique:
- Pour augmenter le réalisme, on souhaite avoir un placement de bâtiments sans grille. Cependant, on veut un système de snapping près d'autres bâtiments.

-Rotation des cubes : on souhaite que le cube tourne de 90° lorsque l'on appuie sur R

**Comment by Jeremy-afk** [comment]
Shotgun
